# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: research
    weight: 11
  - name: Publications
    url: publication
    weight: 12
  - name: News
    url: news
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: For Students
    url: students
    weight: 35
  - name: Projects
    url: projects
    weight: 36
  - name: Events
    url: events
    weight: 40
  - name: Tools
    url: tools
    weight: 45
  - name: Tags
    url: tags
    weight: 50
