baseURL: "https://nlp-unibo.github.io"
title: Language Technologies Lab
theme: ["hugo-redirect", "PaperMod"]

enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: People
          url: people/
          weight: 2
        - name: News
          url: news/
          weight: 3
        - name: For Students
          url: students/
          weight: 4
        - name: Projects
          url: projects/
          weight: 5
        - name: Events
          url: events/
          weight: 6
        - name: Tools
          url: tools/
          weight: 7
        - name: Tags
          url: tags/
          weight: 8

params:
    description: "We are a research group of the Department of Computer Science and Engineering of the University of Bologna. Our focus is natural language processing research and application. We contribute to several national and international research projects and offer a variety of NLP learning activities at the international masters degree in Artificial Intelligence and elsewhere."
    author: Language Technologies Lab
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: true
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","people","news","for students","projects","events","tools"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Language Technologies Lab
          subtitle: "We are a research group of the Department of Computer Science and Engineering of the University of Bologna. Our focus is natural language processing research and application. We contribute to several national and international research projects and offer a variety of NLP learning activities at the international masters degree in Artificial Intelligence and elsewhere."
          imageUrl: "ltlab.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
          - name: Research
            url: research/
          - name: People
            url: people/
          - name: News
            url: news/
          - name: For Students
            url: students/
          - name: Projects
            url: projects/
          - name: Events
            url: events/
          - name: Tools
            url: tools/
          - name: Tags
            url: tags/

    socialIcons:
        - name: GitHub
          url: https://github.com/nlp-unibo
        - name: Email
          url: mailto:unibo.nlp@gmail.com
        - name: Institutional Website
          url: https://site.unibo.it/nlp/en

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Language Technologies Lab"
      icon: favicon.ico
      iconHeight: 18

markup:
    blackFriday:
      angledQuotes: false
      extensions: null
      extensionsMask: null
      footnoteAnchorPrefix: ""
      footnoteReturnLinkContents: ""
      fractions: true
      hrefTargetBlank: false
      latexDashes: true
      nofollowLinks: false
      noreferrerLinks: false
      plainIDAnchors: true
      skipHTML: false
      smartDashes: true
      smartypants: true
      smartypantsQuotesNBSP: false
      taskLists: true
    defaultMarkdownHandler: goldmark
    goldmark:
      extensions:
        definitionList: true
        footnote: true
        linkify: true
        strikethrough: true
        table: true
        taskList: true
        typographer: true
      parser:
        attribute: true
        autoHeadingID: true
        autoHeadingIDType: github
      renderer:
        hardWraps: false
        unsafe: true
        xHTML: false
    highlight:
      codeFences: true
      guessSyntax: true
      hl_Lines: ""
      lineNoStart: 1
      lineNos: false
      lineNumbersInTable: true
      noClasses: true
      style: autumn
      tabWidth: 4
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2